Fix quoting issue in preamble YAML
Causes jekyll's yaml parser to fail with:
```
Error: [...] mapping values are not allowed in this context at line 5 column 15
```